name: release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install node dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
